# Copyright 2022 Berezi Amubieta - AvanzOSC
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).

{
    "name": "Custom MRP Descarga",
    "version": "14.0.1.0.0",
    "category": "MRP",
    "license": "AGPL-3",
    "author": "AvanzOSC",
    "website": "https://github.com/avanzosc/mrp-addons",
    "depends": [
        "custom_mrp_line_cost",
        "custom_descarga",
        "custom_breeding_apps",
        "mrp_production_deconstruction",
        "custom_saca_intercompany",
        "mrp_bom_category",
        "custom_saca_timesheet",
        "stock_move_line_cost",
        "stock_picking_batch_liquidation",
        "stock_picking_cancel",
        "stock_move_in_out_qty",
        "mrp_production_date",
        "stock_inventory_import_cost",
    ],
    "data": [
        "data/quartering_product.xml",
        "data/ir_sequence.xml",
        "data/mrp_bom_category.xml",
        "data/ir_cron_data.xml",
        "views/saca_line_view.xml",
        "views/mrp_production_view.xml",
        "views/stock_production_lot_view.xml",
        "views/stock_quant_view.xml",
        "views/mrp_bom_view.xml",
        "views/product_template_view.xml",
        "views/stock_move_line_view.xml",
        "views/killing_cost_view.xml",
        "report/mrp_production_summary_xlsx.xml",
        "report/mrp_production_quartering_summary_xlsx.xml",
    ],
    "installable": True,
    "auto_install": True,
}
