from . import mrp_workcenter
from . import mrp_bom
from . import product_template
from . import res_company
from . import res_config_settings
from . import order_olaser_lista
from . import order_olaser
from . import order_olaser_tiempos
from . import order_olaser_rechazo
from . import stock_move
from . import mrp_production
from . import mrp_workorder
from . import stock_warehouse_orderpoint
