# Copyright 2024 Alfredo de la Fuente - AvanzOSC
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
from odoo import _, fields, models


class SaleOrder(models.Model):
    _inherit = "sale.order"

    all_sale_production_ids = fields.One2many(
        comodel_name="mrp.production",
        inverse_name="sale_id",
        copy=False,
    )
    count_all_sale_productions = fields.Integer(
        string="Num. All Sale Productions",
        compute="_compute_count_all_sale_productions",
    )

    def _compute_count_all_sale_productions(self):
        for production in self:
            production.count_all_sale_productions = len(
                production.all_sale_production_ids
            )

    def action_view_all_mrp_productions(self):
        self.ensure_one()
        action = {"res_model": "mrp.production", "type": "ir.actions.act_window"}
        if len(self.all_sale_production_ids) == 1:
            action.update(
                {
                    "view_mode": "form",
                    "res_id": self.all_sale_production_ids.id,
                }
            )
        else:
            action.update(
                {
                    "name": _("Manufacturing Orders Generated by %s", self.name),
                    "domain": [("id", "in", self.all_sale_production_ids.ids)],
                    "view_mode": "tree,form",
                }
            )
        return action
